version: '3'

services:
  db:
    image: rethinkdb
    volumes:
      - .:/data
    ports:
      - "8080:8080"
      #- "28015:28015"
  tornado:
    build: .
    command: python app.py
    volumes:
      - .:/usr/src/app
    ports:
      - "8888:8888"
    depends_on:
      - db